# Generated by Django 4.0.2 on 2022-02-25 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("blog", "0003_auto_20191216_1230")]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name": "Autor", "verbose_name_plural": "Autores"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Post", "verbose_name_plural": "Posts"},
        ),
    ]
