version: "3"

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - pgsql
    volumes:
      - /home/drack/Github/Testes/Python/Django-Admin/.dbdata/PGSQL:/data/postgres

  pgadmin:
    container_name: db_admin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - /home/drack/Github/Testes/Python/Django-Admin/.dbdata/PGADMIN:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - pgsql
    depends_on:
      - db

  redis:
    image: redis
    command: redis-server
    container_name: redis-server
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      #- REDIS_PASSWORD=password123
      #- REDIS_MASTER_PASSWORD=masterpassword12
    ports:
      - "6379:6379"
    links:
      - db
    depends_on:
      - db
    networks:
      - pgsql

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    networks:
      - pgsql
    links:
      - db
      - redis
    depends_on:
      - db
      - pgadmin
      - redis

networks:
  pgsql:
    driver: bridge
