# Generated by Django 4.0.2 on 2022-02-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
            ],
        ),
        migrations.CreateModel(
            name="Vaga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
                ("salario", models.FloatField()),
                ("local", models.CharField(max_length=50)),
                ("quantidade", models.IntegerField()),
                ("contato", models.EmailField(max_length=254)),
                (
                    "tipo_contratacao",
                    models.CharField(
                        choices=[
                            ("CLT", "Empregado registrado."),
                            ("PJ", "Pessoa Jurídica"),
                        ],
                        max_length=3,
                    ),
                ),
                ("tecnologias", models.ManyToManyField(to="api.Tecnologia")),
            ],
        ),
    ]
