# Generated by Django 3.0.7 on 2022-02-24 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("clientes", "0005_auto_20190408_1309")]

    operations = [
        migrations.AlterModelOptions(
            name="cliente",
            options={"verbose_name": "Cliente", "verbose_name_plural": "Clientes"},
        ),
        migrations.AlterModelTable(name="cliente", table="cliente_sistema"),
    ]
