# Generated by Django 3.0.7 on 2022-02-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("clientes", "0006_auto_20220224_2036")]

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                ("id_funcionario", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=50)),
            ],
        )
    ]
