# Generated by Django 3.0.7 on 2022-02-24 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("clientes", "0007_funcionario")]

    operations = [
        migrations.AlterModelOptions(
            name="cliente",
            options={
                "ordering": ["data_nascimento"],
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        )
    ]
